PTBusToSchool/PtBusToSchool/Models/Emergency.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace PtBusToSchool.Models
{
    public class Emergency : BackendBase
    {
        [Key]
        [Display(Name = "編號")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonProperty]
        public int Id { get; set; }

        [Required(ErrorMessage = "{0}必填")]
        [MaxLength(50)]
        [Display(Name = "事件名稱")]
        public string Subject { get; set; }

         [Required(ErrorMessage = "{0}必填")]
        [Display(Name = "事發日期")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime? IncidentDate { get; set; }


         [Display(Name = "路線")]
         public string Line { get; set; }


         [Display(Name = "班次")]
         public string CarNo { get; set; }


         [Display(Name = "原因")]
         public string Momo { get; set; }
      

    }
}

PTBusToSchool/PtBusToSchool/Controllers/EmergencyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using MvcPaging;
using System.Web.Mvc;
using PtBusToSchool.Filters;
using PtBusToSchool.Models;

namespace PtBusToSchool.Areas.admin.Controllers
{
	[PermissionFilters]
    [Authorize]
    public class EmergencyController : _BaseController
    {
        private BackendContext _db = new BackendContext();
        private const int DefaultPageSize = 15;
        //

        


        public ActionResult Index(int? page, FormCollection fc )
        {
			//記住搜尋條件
            GetCatcheRoutes(page, fc);

            //取得正確的頁面
            int currentPageIndex = getCurrentPage(page, fc);
            

            var emergency = _db.Emergency.OrderByDescending(p => p.InitDate).AsQueryable();
            if (hasViewData("SearchBySubject")) 
            { 
            string searchBySubject = getViewDateStr("SearchBySubject");             
                emergency = emergency.Where(w => w.Subject.Contains(searchBySubject)); 
            }
            if (hasViewData("SearchByStartDate"))
            {
                DateTime Date = Convert.ToDateTime(getViewDateStr("SearchByStartDate"));

                emergency = emergency.Where(w => w.IncidentDate == Date);
            }

//            ViewBag.Subject = Subject;
            return View(emergency.OrderByDescending(p => p.InitDate).ToPagedList(currentPageIndex, DefaultPageSize));

        }



        

        //
        // GET: /admin/Emergency/Details/5

        public ActionResult Details(int id = 0)
        {
            Emergency emergency = _db.Emergency.Find(id);
            if (emergency == null)
            {
                //return HttpNotFound();
				 return View();
            }
            return View(emergency);
        }

        //
        // GET: /admin/Emergency/Create

        public ActionResult Create()
        {

            return View();
        }


        public JsonResult GetCarNo(int LineId)
        {
           
            List<KeyValuePair<string, string>> items = new List<KeyValuePair<string, string>>();


            var sendcar = _db.SendCars.Where(x => x.ParentId == LineId).ToList();


            if (sendcar.Any())
            {
                foreach (var item in sendcar)
                {
                    string[] timearr = item.CarNoTime.Time.Split('、');

                    items.Add(new KeyValuePair<string, string>(
                        item.Id.ToString(),
                        string.Format("{0}", item.CarNoTime.CarNo + "(" + timearr[0] + ")")));
                }
            }

            return this.Json(items);
        }



        public JsonResult GetCarLine(DateTime datetext)
        {
           
            List<KeyValuePair<string, string>> items = new List<KeyValuePair<string, string>>();


            var sendcar = _db.SendCars.FirstOrDefault(x => x.StartDate == datetext.Date);
            var carline = _db.SendCars.Where(x => x.ParentId == sendcar.Id).ToList();

            if (carline.Any())
            {
                foreach (var item in carline)
                {
                    items.Add(new KeyValuePair<string, string>(
                        item.Id.ToString(),
                        string.Format("{0}", item.LineName.Subject+"("+item.LineName.Line+")")));
                }
            }

            return this.Json(items);
        }

        //
        // POST: /admin/Emergency/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create(Emergency emergency )
        {

            int Carlineid = Convert.ToInt16(emergency.Line);
            int CarNo = Convert.ToInt16(emergency.CarNo);
            var carline = _db.SendCars.Find(Carlineid);
            var carNo = _db.SendCars.Find(CarNo);


            emergency.Line = carline.LineName.Subject + "(" + carline.LineName.Line + ")";

            string[] timearr = carNo.CarNoTime.Time.Split('、');
            emergency.CarNo = carNo.CarNoTime.CarNo + "(" + timearr[0] + ")";





            if (ModelState.IsValid)
            {

                _db.Emergency.Add(emergency);
                emergency.Create(_db,_db.Emergency);
                return RedirectToAction("Index");
            }

            return View(emergency);
        }

        //
        // GET: /admin/Emergency/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Emergency emergency = _db.Emergency.Find(id);
            if (emergency == null)
            {
                return HttpNotFound();
            }
            return View(emergency);
        }

        //
        // POST: /admin/Emergency/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
         
        public ActionResult Edit(Emergency emergency)
        {
            if (ModelState.IsValid)
            {

               //_db.Entry(emergency).State = EntityState.Modified;
                emergency.Update();
                return RedirectToAction("Index",new{Page=-1});
            }
            return View(emergency);
        }

        //
        // GET: /admin/Emergency/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Emergency emergency = _db.Emergency.Find(id);
            if (emergency == null)
            {
                return HttpNotFound();
            }
            return View(emergency);
        }

        //
        // POST: /admin/Emergency/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Emergency emergency = _db.Emergency.Find(id);
            _db.Emergency.Remove(emergency);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }

}

PTBusToSchool/PtBusToSchool/Views/Emergency/Create.cshtml
@using PtBusToSchool.Models
@model PtBusToSchool.Models.Emergency

@{
    ViewBag.Title = "新增";
}

<h2>新增</h2>

    @using (Html.BeginForm()) {

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @ViewBag.Message
    <fieldset>
        <legend>Emergency</legend>
        <div>
        <label for="">
            @Html.LabelFor(model => model.Subject)
        </label>
            @Html.TextBoxFor(model => model.Subject,new { placeholder=ModelsAttributeHelper<PtBusToSchool.Models.Emergency>.GetDisplayName("Subject") })
           <div> @Html.ValidationMessageFor(model => model.Subject)</div>
        </div>
        <div>
       <label for="">
            @Html.LabelFor(model => model.IncidentDate)
        </label>
            @Html.TextBoxFor(model => model.IncidentDate,"{0:d}",new {@class="datepicker",target="" })
           <div> @Html.ValidationMessageFor(model => model.IncidentDate)</div>
        </div>

        <div>
            @Html.LabelFor(model => model.Line)
         @*   @Html.TextBoxFor(model => model.Line,new { placeholder=ModelsAttributeHelper<PtBusToSchool.Models.Emergency>.GetDisplayName("Line") })*@
         
         <select id="Line" name="Line">
            <option>------</option>
        </select>
               <div>@Html.ValidationMessageFor(model => model.Line)</div>
        </div>

        <div>
            @Html.LabelFor(model => model.CarNo)
         <select id="CarNo" name="CarNo" >
            <option>------</option>
        </select>
            @*@Html.TextBoxFor(model => model.CarNo, new {placeholder = ModelsAttributeHelper<PtBusToSchool.Models.Emergency>.GetDisplayName("CarNo")})*@
           <div> @Html.ValidationMessageFor(model => model.CarNo)</div>
        </div>

        <div>
           <label for=""> @Html.LabelFor(model => model.Momo)
           @Html.TextAreaFor(model => model.Momo, new {@style = "height: 100px; width:800px;", placeholder = ModelsAttributeHelper<PtBusToSchool.Models.Emergency>.GetDisplayName("Momo")})
           <div> @Html.ValidationMessageFor(model => model.Momo)</div>
        </div>

        <div class="confirm-group">
            <input class="btn btn-primary" type="submit" value="新增" />
            <input class="btn btn-primary" type="button" onclick="history.back()" value="回到上一頁" />
        </div>
    </fieldset>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
    <script>
        $(document).ready(function() {
            $(".datepicker").datepicker({
                onSelect: function (dateText) {
                   GetCarLine(dateText);
                }
            });
            $('#Line').change(function () {
              
               
                GetLineId();
            });
        });
        function GetLineId() {

            var selectedValue = $('#Line option:selected').val();
            if ($.trim(selectedValue).length > 0) {
                alert(selectedValue);
                GetCarNo(selectedValue);
            } else {
                $('#CarNo').empty();
                $('#CarNo').append($('<option></option>').val('').text('請選擇'));
            }


        }

        function GetCarLine(dateText) {
            $.ajax({
                url: '@Url.Action("GetCarLine", "Emergency")',
                data: { dateText: dateText },
                type: 'post',
                cache: false,
                async: false,
                dataType: 'json',
                success: function (data) {
                 
                    if (data.length > 0) {
                        $('#Line').empty();
                        $('#Line').append($('<option></option>').val('').text('請選擇'));
                     
                        $.each(data,
                            function (i, item) {

                                
                                $('#Line').append($('<option></option>').val(item.Key).text(item.Value));
                            });

                    }
                    if (data.length === 0) {
                        $('#Line').empty();
                        $('#Line').append($('<option></option>').val('').text('-------'));

                    }
                }
            });
        }
        function GetCarNo(LineId) {
            $.ajax({
                url: '@Url.Action("GetCarNo", "Emergency")',
                data: { LineId: LineId },
                type: 'post',
                cache: false,
                async: false,
                dataType: 'json',
                success: function (data) {
                    
                    if (data.length > 0) {
                        $('#CarNo').empty();
                        $('#CarNo').append($('<option></option>').val('').text('請選擇'));

                        $.each(data,
                            function (i, item) {


                                $('#CarNo').append($('<option></option>').val(item.Key).text(item.Value));
                            });

                    }
                    if (data.length === 0) {
                        $('#CarNo').empty();
                        $('#CarNo').append($('<option></option>').val('').text('-------'));

                    }
                }
            });
        }


    </script>
    
}

PTBusToSchool/PtBusToSchool/Views/Emergency/Delete.cshtml
@model PtBusToSchool.Models.Emergency

@{
    ViewBag.Title = "刪除";
}

<h2>刪除</h2>

<h3>你確定要刪除嗎?</h3>
<fieldset>
    <legend>Emergency</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Subject)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Subject)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="刪除" /> |
        <input type="button" onclick="history.back()" value="回到上一頁" />
    </p>
}

PTBusToSchool/PtBusToSchool/Views/Emergency/Details.cshtml
@model PtBusToSchool.Models.Emergency

@{
    ViewBag.Title = "內容";
}

<h2>內容</h2>

<fieldset>
    <legend>Emergency內容</legend>
	<table>
	<tr>
	<td colspan="7">
	 PtBusToSchool.Models.Emergency
	</td>

	</tr>
	<tr>
    <td>
         欄位中文名稱
    </td>
    <td>
      欄位名稱
    </td>
	 <td>
       是否主索引
    </td>
	<td>
	是否唯讀
	</td>
	<td>
	 是否外索引
	</td>
	<td>
	型別
	</td>
</tr>

<tr>
    <td>
         @Html.DisplayNameFor(model => model.Subject)
    </td>
    <td>
       Subject
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 String
	</td>
	
</tr>
<tr>
    <td>
         @Html.DisplayNameFor(model => model.IncidentDate)
    </td>
    <td>
       IncidentDate
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 DateTime
	</td>
	
</tr>
<tr>
    <td>
         @Html.DisplayNameFor(model => model.Line)
    </td>
    <td>
       Line
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 String
	</td>
	
</tr>
<tr>
    <td>
         @Html.DisplayNameFor(model => model.CarNo)
    </td>
    <td>
       CarNo
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 String
	</td>
	
</tr>
<tr>
    <td>
         @Html.DisplayNameFor(model => model.Momo)
    </td>
    <td>
       Momo
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 String
	</td>
	
</tr>
<tr>
    <td>
         @Html.DisplayNameFor(model => model.Poster)
    </td>
    <td>
       Poster
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 String
	</td>
	
</tr>
<tr>
    <td>
         @Html.DisplayNameFor(model => model.InitDate)
    </td>
    <td>
       InitDate
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 DateTime
	</td>
	
</tr>
<tr>
    <td>
         @Html.DisplayNameFor(model => model.Updater)
    </td>
    <td>
       Updater
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 String
	</td>
	
</tr>
<tr>
    <td>
         @Html.DisplayNameFor(model => model.UpdateDate)
    </td>
    <td>
       UpdateDate
    </td>
	 <td>
       False
    </td>
	<td>
	 False
	</td>
	
	<td>
	 False
	</td>
	<td>
	 DateTime
	</td>
	
</tr>
</table>
</fieldset>
<p>
    @Html.ActionLink("編輯","Edit", new { id=Model.Id }) |
     <input type="button" onclick="history.back()" value="回到上一頁" />
</p>

PTBusToSchool/PtBusToSchool/Views/Emergency/Edit.cshtml
@using PtBusToSchool.Models
@model PtBusToSchool.Models.Emergency

@{
    ViewBag.Title = "編輯";
}

<h2>編輯</h2>

    @using (Html.BeginForm()) {

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Emergency</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Subject)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Subject,new { placeholder=ModelsAttributeHelper<PtBusToSchool.Models.Emergency>.GetDisplayName("Subject") })
           
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IncidentDate)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.IncidentDate,"{0:d}",new {@class="datepicker",target="" })
            @Html.ValidationMessageFor(model => model.IncidentDate)
           
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Line)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Line,new { placeholder=ModelsAttributeHelper<PtBusToSchool.Models.Emergency>.GetDisplayName("Line") })
           
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CarNo)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CarNo,new { placeholder=ModelsAttributeHelper<PtBusToSchool.Models.Emergency>.GetDisplayName("CarNo") })
           
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Momo)
        </div>
        <div class="editor-field">
           @Html.TextAreaFor(model => model.Momo, new {@style = "height: 100px; width:800px;", placeholder = ModelsAttributeHelper<PtBusToSchool.Models.Emergency>.GetDisplayName("Momo")})
        </div>

            @Html.HiddenFor(model => model.Poster)
            @Html.HiddenFor(model => model.InitDate)
            @Html.HiddenFor(model => model.UpdateDate)
        <p>
            <input type="submit" value="更新" /> <input type="button" onclick="history.back()" value="回到上一頁" />
        </p>
    </fieldset>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
    <script>
        $(document).ready(function() {
            $(".datepicker").datepicker();
        });
    </script>

    }

PTBusToSchool/PtBusToSchool/Views/Emergency/Index.cshtml
@using MvcPaging
@using PtBusToSchool.Helpers
@model MvcPaging.IPagedList<PtBusToSchool.Models.Emergency>

@{
    ViewBag.Title = "即時推播通知管理";
}

<h2>@ViewBag.Title
    <a id="AddEmergency" class="popup_btn btn btn-primary" href="#AddEmergencyPanel">新增推播</a>
</h2>

@*@Html.ActionLink("新增", "Create", new { ParentId = @ViewBag.ParentId }, new { @class = "btn btn-primary" })*@

@using (Html.BeginForm())
{
    <div class="input-text-group">
        <div>
            <label for="">
                @Html.DisplayNameFor(model => model.FirstOrDefault().Subject)
            </label>

            @Html.InputSearchBox("SearchBySubject", ViewData["SearchBySubject"])

            <label for="">推播日期</label>

            <input type="text" name="SearchByStartDate" value="@ViewData["SearchByStartDate"]" class = "datepicker"/>
            <input class="btn btn-primary" type="submit" value="搜尋" />

        </div>
    </div>

    
}

<style>
    .popup_content .input-date-group input:not([type="button"]):not([type="checkbox"]):not([type="radio"]){
        width: 150px;
    }
    .input-date-group select
    {
        width: 50px;
    }
</style>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().IncidentDate)
        </th>
         <th>
          推播人員
        </th>
           <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().State)
        </th>
        @*  <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Line)
        </th>*@
        @* <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().CarNo)<span>(發車時間)</span>
        </th>*@


        <th></th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @if (item.IncidentDate == null)
                    {
                        @item.InitDate.Value.ToString("yyyy/MM/dd HH:mm")
                    }
                    else
                    {
                        @item.IncidentDate.Value.ToString("yyyy/MM/dd HH:mm")

                    }

                </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.Poster)
                </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                @* <td>
            @Html.DisplayFor(modelItem => item.Line)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarNo)
        </td>*@

                <td>
                    @* @Html.ActionLink("編輯", "Edit", new { id=item.Id }) |*@
                    @*@Html.ActionLink("內容", "Details", new { id=item.Id }) | *@
                    @* @Html.ActionLink("刪除", "Delete", new { id=item.Id }) *@
                    @Html.Hidden("ID", item.Id)
                    <input type="button" class="popup_btn EmergencyDetail btn btn-primary"  id="@item.Id" href="#EmergencyDetailPanel" value="詳細資料"/>
                </td>
            </tr>
        }
    </tbody>
</table>
<div id="AddEmergencyPanel" class="popup_background">
    <div class="popup_content animated bounceInUp">
        <div class="closepop">
            <img width="30" height="30" src="~/images/close-btn.svg" alt="">
            <h3 style="color: white">新增推播</h3>
        </div>
        <div class="banner">
            <div class="popup_tip">
                <div class="input-radio-group">
                    <div>
                        <label><font color="red">*</font>推播類型</label>
                        <input type="radio" name="State" class="State" checked="checked" value="0">
                        即時推播
                            <input type="radio" name="State" class="State" value="1">
                            特定日期推播
                    </div>
                </div>
                <div class="input-date-group">
                    <div id="IncidentDateShow">
                        <label for=""><font color="red">*</font>推播日期</label>
                        <input type="text" id="IncidentDate" name="IncidentDate" class="datepicker" />
                            <select name="" id="Hours">
                                @for (int k = 0; k <= 23; k++)
                                {
                                    if (k < 10)
                                    {
                                    <option value=0@(k)>0@(k)</option>
                                    }
                                    else
                                    {
                                    <option value=@k>@k</option>
                                    }

                                }

                            </select>
                        <span>時</span>
                            <select name="" id="Minutes">
                                @for (int k = 0; k <= 59; k++)
                                {
                                    if (k < 10)
                                    {
                                    <option value=0@(k)>0@(k)</option>
                                    }
                                    else
                                    {
                                    <option value=@k>@k</option>
                                    }

                                }

                            </select>
                        <span>分</span>
                        <span style="display: block;margin-left: 140px;color: red;" id="IncidentDatemessage"></span>
                    </div>
                </div>
                <div class="input-text-group">
                    <div>
                        <label for=""><font color="red">*</font>推播主題</label>
                        <input id="Subject" name="Subject" />
                        <span id="Subjectmessage" style="color: red"></span>
                    </div>
                    <div>
                        <label for=""><font color="red">*</font>推播內容</label>
                          <textarea id="Momo" cols="50" rows="5" placeholder="請輸入詳細的內容通知..."></textarea>
                        <span id="Momomessage" style="color: red"></span>
                    </div>
                </div>
                <div class="confirm-group">
                    <a href="" class="btn btn-primary">取消</a>
                    <input id="CreateEmergency" class="btn btn-success CreateCar" type="button" value="確定" />
                </div>

            </div>
        </div>
    </div>
</div>

<div id="EmergencyDetailPanel" class="popup_background">
    <div class="popup_content animated bounceInUp">
        <div class="closepop">
            <img width="30" height="30" src="~/images/close-btn.svg" alt="">
            <h3 style="color: white">推播詳情</h3>
        </div>
        <div class="banner">
            <div class="popup_tip">
                   <div id="EmergencyPoster" align="right">
                       
                       </div>
                <div class="input-text-group">

                    <div>
                        <label for="">推播日期</label>
                        <input id="EmergencyDetailIncidentDate" disabled>
                    </div>
                    <div>
                        <label for="">推播類型</label>
                        <input id="EmergencyState" disabled>
                    </div>
                    <div>
                        <label for="">推播主題</label>
                        <input id="EmergencyDetailSubject" disabled>
                    </div>

                    <div>
                        <label for="">推播內容</label>
                        <textarea id="EmergencyDetailMomo" cols="50" rows="5" disabled></textarea>

                    </div>

                </div>


            </div>
        </div>
    </div>
</div>





<div class="pager">
    @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount)
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker();
            $("#IncidentDateShow").hide();
        });

        $(".State").change(function () {
            var state = $("[name=State]:radio:checked").val();

            if (state === "1") {
                $("#IncidentDateShow").show();
            } else {
                $("#IncidentDateShow").hide();
            }


        });
        $("#CreateEmergency").click(function () {
            var state = $("[name=State]:radio:checked").val();
            var statestr = "";
            if (state === "1") {
                statestr = "特定日期推播";
                if ($("#IncidentDate").val() !== "") {
                    var StartDateValid = dateValidationCheck($("#IncidentDate").val());
                    if (StartDateValid) {
                        $("#IncidentDatemessage").text("");
                    } else {
                        $("#IncidentDatemessage").text("請輸入 YYYY/MM/DD 日期格式");
                    }
                } else {
                    $("#IncidentDatemessage").text("請選擇日期或輸入日期");
                }
            } else {
                statestr = "即時推播";
            }


            if ($("#Subject").val() === "") {
                $("#Subjectmessage").text("請輸入事件名稱");
            } else {
                $("#Subjectmessage").text("");
            }
            if ($("#Momo").val() === "") {
                $("#Momomessage").text("請輸入事件內容");
            } else {
                $("#Momomessage").text("");
            }

            if ($("#Momomessage").text() === "" && $("#Subjectmessage").text() === "" && $("#IncidentDatemessage").text() === "") {
                var formData = new FormData();
                formData.append('IncidentDate', $("#IncidentDate").val());
                formData.append('Subject', $("#Subject").val());
                formData.append('Momo', $("#Momo").val());
                formData.append('State', statestr);
                formData.append('Hours', $("#Hours").val());
                formData.append('Minutes', $("#Minutes").val());

                $.ajax({
                    url: '@Url.Action("AddEmergency", "Emergency")',
                    data: formData,
                    type: 'post',
                    contentType: false, // 告诉jQuery不要去這置Content-Type
                    processData: false, // 告诉jQuery不要去處理發送的數據 
                    cache: false,
                    async: false,
                    dataType: 'json',
                    success: function (data) {
                        if (data["Message"] === "Success") {
                            $(".popup_tip").hide();
                            alert("新增成功");
                            location.href = '@Url.Action("index", "Emergency")';
                        } else {
                            alert("新增失敗");
                        }
                    }
                });
            }
        });
        $(".EmergencyDetail").click(function () {

            var EmergencyId = $(this).attr('Id');

            $.ajax({
                url: '@Url.Action("GetEmergencyDetail", "Emergency")',
                data: { EmergencyId: EmergencyId },
                type: 'post',
                cache: false,
                async: false,
                dataType: 'json',
                success: function (data) {
                    $("#EmergencyDetailIncidentDate").val(data["IncidentDate"]);
                    $("#EmergencyDetailSubject").val(data["Subject"]);
                    $("#EmergencyDetailMomo").val(data["Momo"]);
                    $("#EmergencyState").val(data["State"]);
                    $("#EmergencyPoster").text("由"+data["Poster"]+"推播");
                }

            });
        });


    </script>
}