PTBusToSchool/PtBusToSchool/Models/SendCar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace PtBusToSchool.Models
{
    public class SendCar :BackendBase
    {
        [Key]
        [Display(Name = "編號")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonProperty]
        public int Id { get; set; }

          //ForeignKey
        [Display(Name = "上層編號")]
        public int? ParentId { get; set; }

        [JsonIgnore]
        [ForeignKey("ParentId")]
        public virtual SendCar ParentSendCar { get; set; }


          [Display(Name = "發車日期")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime? StartDate { get; set; }


       //ForeignKey
        [Display(Name = "路線名稱")]
        public int? CarLineId { get; set; }

        [ForeignKey("CarLineId")]
        [JsonIgnore]
        public virtual CarLine LineName { get; set; }

        //ForeignKey
        [Display(Name = "班次")]
        public int? TimeScheduleId { get; set; }

        [ForeignKey("TimeScheduleId")]
        [JsonIgnore]
        public virtual TimeSchedule CarNoTime { get; set; }

        [Display(Name = "預約人數")]
        public string People { get; set; }

        [Display(Name = "候補人數")]//已達每站車上最大容客量
        public string NoReservationPeople { get; set; }

        [Display(Name = "派車數")]
        public int? CarNum { get; set; }

        [Display(Name = "上上層")]
        public int? GrandParentId { get; set; }

        [Display(Name = "派車")]
        public string Cars { get; set; }

        [Display(Name = "載客數")]
        public int? Passengers { get; set; }

        [Display(Name = "駕駛")]
        public string Drivers { get; set; }

        [Display(Name = "層級")]
        [NotMapped]
        public int Level
        {
            get
            {
                int level = 1;
                SendCar parentClass = this.ParentSendCar;
                while (parentClass != null)
                {
                    level++;
                    parentClass = parentClass.ParentSendCar;
                }

                return level;
            }

        }



        public virtual ICollection<SendCar> ChildSendCar{ get; set; }
    }

    
}

PTBusToSchool/PtBusToSchool/Controllers/SendCarController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using MvcPaging;
using System.Web.Mvc;
using PtBusToSchool.Filters;
using PtBusToSchool.Models;

namespace PtBusToSchool.Areas.admin.Controllers
{
	[PermissionFilters]
    [Authorize]
    public class SendCarController : _BaseController
    {
        private BackendContext _db = new BackendContext();
        private const int DefaultPageSize = 15;
        //




	    public ActionResult Index(int? page, FormCollection fc, int? id,DateTime? date)
	    {
             var sendCarcount = _db.SendCars.Where(x => x.StartDate >= DateTime.Today);
	       
             if (sendCarcount.Count()!=14)
	        {
                DateTime dt = DateTime.Now.Date;
	            for (int i = 0; i < 14; i++)
	            {
                    initcarinfo(dt.AddDays(i));
	            }
             
	        }
	        if (id != null&& id!=0)
	        {
                SendCar sendCarlevel = _db.SendCars.Find(id);
                if (sendCarlevel.Level == 2)
                {
                    Reservationreset(sendCarlevel.ParentSendCar.StartDate);
                }
	        }
	   
	        //記住搜尋條件
	        if (id.HasValue && id != 0)
	        {
	        }
	        else
	        {
	        
	        GetCatcheRoutes(page, fc);
	    }

	    //取得正確的頁面
            int currentPageIndex = getCurrentPage(page, fc);

	        Session["Id"] = null;
            var sendcars = _db.SendCars.Include(s => s.ParentSendCar).Include(s => s.LineName).Include(s => s.CarNoTime).OrderByDescending(p => p.InitDate).AsQueryable();

            ViewBag.CarLineId = new SelectList(_db.CarLine.Where(p=>p.ParentId==null).OrderBy(p=>p.InitDate), "Id", "Subject");
            ViewBag.StartDate = new SelectList(_db.SendCars.Where(p => p.ParentId == null).OrderBy(p => p.InitDate), "Id", "StartDate");
            if (id.HasValue && id != 0)
            {
                SendCar sendCar = _db.SendCars.Find(id);
                if (sendCar.Level == 1)
                {
                    ViewBag.linename = id;
                    sendcars = sendcars.Where(x => x.ParentId == id);
                    ViewBag.Path = "→" + sendCar.StartDate.GetValueOrDefault().Date.ToString("yyyy/MM/dd");
                    
                }
                if (sendCar.Level == 2)
                {
                    var carline = _db.CarLine.Find(sendCar.CarLineId);
                    //ViewBag.grandparentid = sendCar.ParentId;
                    ViewBag.carnotime = carline.Line;
                    sendcars = sendcars.Where(x => x.GrandParentId == sendCar.ParentId&&x.ParentId==id);
                    ViewBag.Path = "→" + sendCar.ParentSendCar.StartDate.GetValueOrDefault().Date.ToString("yyyy/MM/dd")+"→" + sendCar.LineName.Subject;
                }
            }
            else
            {
                sendcars = sendcars.Where(x => x.ParentId == null);

            }
         
            if (hasViewData("SearchByStartDate"))
            {
               
                DateTime searchByStartDate = Convert.ToDateTime(getViewDateStr("SearchByStartDate"));
                sendcars = sendcars.Where(w => w.StartDate == searchByStartDate);
            } 
          


            return View(sendcars.OrderByDescending(p => p.StartDate).ToPagedList(currentPageIndex, DefaultPageSize));
           
        }

        private void Reservationreset(DateTime? date)
	    {
            SendCar sendCar = _db.SendCars.FirstOrDefault(x => x.StartDate == date);
	        var sendCarchild = _db.SendCars.Where(x => x.ParentId == sendCar.Id).ToList();
            var studentReservation =
                _db.StudentReservation.Where(
                    x => x.ReservationDate == date && x.ReservationStatus != ReservationState.取消預約);

	        foreach (var item in sendCarchild)
            {
                string[] getsitecount = item.LineName.Line.Split('→');
                var timeschedule = _db.TimeSchedule.Where(x => x.CarLineId == item.CarLineId && x.ParentId != null).ToList();
                string carlineid = item.CarLineId + "";
                string people = "";
                for (int j = 0; j < getsitecount.Length; j++)
                {
                    people = people + "0:0";
                    if (j != getsitecount.Length - 1)
                    {
                        people += "、";
                    }


                }
                
             
                foreach (var items in timeschedule)
                {

                    ArrayList addcolumn = new ArrayList();
                    ArrayList cutcolumn = new ArrayList();
                    for (int i = 0; i < getsitecount.Length; i++)
                    {
                        addcolumn.Add(0);
                        cutcolumn.Add(0);
                    }

                    foreach (var reservationitem in studentReservation.Where(x => x.ReservationCarNo == items.CarNo && x.ReservationCarLine == carlineid && x.ReservationStatus != ReservationState.取消預約))
                    {
                            for (int j = 0; j < getsitecount.Length; j++)
                            {
                                if (reservationitem.Startstation == getsitecount[j])
                                {
                                    addcolumn[j] = Convert.ToInt16(addcolumn[j]) + 1;

                                    break;
                                }

                            }
                        
                        for (int j = 0; j < getsitecount.Length; j++)
                        {
                            if (reservationitem.Endstation == getsitecount[j])
                            {
                                cutcolumn[j] = Convert.ToInt16(cutcolumn[j]) + 1;

                                break;
                            }

                        }
                        people = "";
                        for (int i = 0; i < addcolumn.Count; i++)
                        {
                            people += addcolumn[i] + ":" + cutcolumn[i];
                            if (i != addcolumn.Count - 1)
                            {
                                people += "、";
                            }
                        }

                    }
                   
                    var sendCargrandchild =
                        _db.SendCars.FirstOrDefault(
                            x => x.GrandParentId == sendCar.Id && x.ParentId == item.Id && x.TimeScheduleId == items.Id);
                    if (!string.IsNullOrEmpty(people))
                    {
                        sendCargrandchild.People = people;
                       
                        people = "";
                    }
                    else
                    {
                        for (int j = 0; j < getsitecount.Length; j++)
                        {
                            people = people + "0:0";
                            if (j != getsitecount.Length - 1)
                            {
                                people += "、";
                            }


                        }
                        sendCargrandchild.People = people;
                       
                    }





                    //addcolumn.Clear();
                    // cutcolumn.Clear();
                    //for (int i = 0; i < getsitecount.Length; i++)
                    //{
                    //    addcolumn.Add(0);
                    //    cutcolumn.Add(0);
                    //}

                    //foreach (var reservationitem in studentReservation.Where(x => x.ReservationCarNo == items.CarNo && x.ReservationCarLine == carlineid && x.ReservationStatus == ReservationState.候補))
                    //{
                    //    for (int j = 0; j < getsitecount.Length; j++)
                    //    {
                    //        if (reservationitem.Startstation == getsitecount[j])
                    //        {
                    //            addcolumn[j] = Convert.ToInt16(addcolumn[j]) + 1;

                    //            break;
                    //        }

                    //    }

                    //    for (int j = 0; j < getsitecount.Length; j++)
                    //    {
                    //        if (reservationitem.Endstation == getsitecount[j])
                    //        {
                    //            cutcolumn[j] = Convert.ToInt16(cutcolumn[j]) + 1;

                    //            break;
                    //        }

                    //    }
                    //    people = "";
                    //    for (int i = 0; i < addcolumn.Count; i++)
                    //    {
                    //        people += addcolumn[i] + ":" + cutcolumn[i];
                    //        if (i != addcolumn.Count - 1)
                    //        {
                    //            people += "、";
                    //        }
                    //    }

                    //}

                 
                    //if (!string.IsNullOrEmpty(people))
                    //{
                    //    sendCargrandchild.NoReservationPeople = people;
                    //    _db.SaveChanges();
                    //    people = "";
                    //}
                    //else
                    //{
                    //    for (int j = 0; j < getsitecount.Length; j++)
                    //    {
                    //        people = people + "0:0";
                    //        if (j != getsitecount.Length - 1)
                    //        {
                    //            people += "、";
                    //        }


                    //    }
                    //    sendCargrandchild.NoReservationPeople = people;
                        _db.SaveChanges();
                    //}
























                 

PTBusToSchool/PtBusToSchool/Views/SendCar/Arrangeshifts.cshtml
@using MvcPaging
@using PtBusToSchool.Helpers
@using PtBusToSchool.Models
@model IQueryable<SendCar>

@{
    ViewBag.Title = "班表";
    List<Driver> driverlist = ViewBag.drivers;
    List<SendCar> sendCars = Model.ToList();
    var linename = "";
}

@if (ViewBag.select){
<h2>@ViewBag.date 班表 <input type="button" class="btn btn-primary" id="backSendcar" value="回派遣列表"/></h2>
}else{
<h2>班表 <input type="button" class="btn btn-primary" id="backSendcar" value="回派遣列表"/></h2>
}
@using (Html.BeginForm())
{
    <div class="input-text-group">
        <div>
            <label for="">
                @Html.DisplayNameFor(model => model.FirstOrDefault().Drivers)
            </label>
            @Html.InputSearchBox("SearchByDrivers", ViewData["SearchByDrivers"])
            <label for="">
                @Html.DisplayNameFor(model => model.FirstOrDefault().Cars)
            </label>
            @Html.InputSearchBox("SearchByCars", ViewData["SearchByCars"])

            <input class="btn btn-primary" type="submit" value="搜尋" />


        </div>
    </div>

}
<input id="ClassId" class="ClassId" value="@Request.Url.Segments[3]" type="hidden" />

<div style="height: 40px;"></div>

@if (ViewBag.select)
{
  
    <table class="table">
        <tr>
            <th>
               路線
            </th>
            @*<th> @Html.DisplayNameFor(model => model.FirstOrDefault().TimeScheduleId)</th>*@
            <th>發車時間</th>
            <th>媒合前的派車</th>
            <th>媒合後更換的派車</th>
            <th>媒合前的駕駛</th>

            <th>媒合後更換的駕駛</th>

            <th></th>
        </tr>
        <tbody>
            @foreach (var item in sendCars)
            {
                string[] peoplearr = item.People.Split('、');
                Boolean havepeople = false;
                foreach (var peoplearritem in peoplearr)
                {
                    if (peoplearritem != "0:0")
                    {
                        havepeople = true;
                        break;
                    }
                }
                if (havepeople)
                {

                    <tr>
                        <td>@item.ParentSendCar.LineName.CarId @item.ParentSendCar.LineName.Subject</td>
                        @*<td>@item.CarNoTime.CarNo</td>*@

                        @{ string[] timearr = item.CarNoTime.Time.Split('、');}
                        <td>@timearr[0]</td>
                        @if (item.Cars != null)
                        {
                            string[] carid = item.Cars.Split('、');
                            <td>
                                @for (int i = 0; i < carid.Length; i++)
                                {
                                    <div>@carid[i]</div>
                                }
                            </td>
                        }
                        else
                        {
                            <td>選擇不派車</td>
                        }
                        @if (item.ChangeCars != null)
                        {
                            string[] carid = item.ChangeCars.Split('、');
                            <td>
                                @for (int i = 0; i < carid.Length; i++)
                                {
                                    <div style="color: red">@carid[i]</div>
                                }
                            </td>
                        }
                        else
                        {
                            <td></td>
                        }

                        @if (item.Drivers != null)
                        {
                            string[] drivers = item.Drivers.Split('、');
                            <td>
                                @for (int i = 0; i < drivers.Length; i++)
                                {
                                    int driverId = Convert.ToInt16(drivers[i]);
                                    foreach (var driverlistitem in driverlist.Where(x => x.Id == driverId))
                                    {
                                        <div>@driverlistitem.Subject</div>
                                    }

                                }
                            </td>
                        }
                        else
                        {
                            <td>無</td>
                        }

                        @if (item.ChangeDrivers != null)
                        {
                            string[] drivers = item.ChangeDrivers.Split('、');
                            <td>
                                @for (int i = 0; i < drivers.Length; i++)
                                {
                                    int driverId = Convert.ToInt16(drivers[i]);
                                    foreach (var driverlistitem in driverlist.Where(x => x.Id == driverId))
                                    {
                                        <div style="color: red">@driverlistitem.Subject</div>
                                    }

                                }
                            </td>
                        }
                        else
                        {
                            <td></td>
                        }

                        <td>
                            @if (ViewBag.Have)
                            {
                                DateTime sendcartime = Convert.ToDateTime(item.ParentSendCar.ParentSendCar.StartDate.GetValueOrDefault().Date.ToString("yyyy/MM/dd") + " " + Convert.ToDateTime(timearr[0]).ToString("HH:mm"));
                                if (DateTime.Now < sendcartime)
                                {
                                    <input type="button" class="popup_btn btn btn-primary change" id="@item.Id" href="#ChangePanel" value="更換駕駛或車子"/>
                                }

                            }

                        </td>
                    </tr>
                      }
            }



        </tbody>
    </table>

}

else
{
    foreach (var item in sendCars.Where(x => x.Level == 2))
    {
        if (item.ChildSendCar.Where(x => x.ParentId == item.Id).Any())
        {

    <h3>

       @ViewBag.date @item.LineName.CarId (@item.LineName.Subject)

    </h3>

    <table class="table">
        <tr>

            @*<th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().TimeScheduleId)
            </th>*@
            <th>發車時間</th>
            <th>發車車牌號碼</th>
            <th>駕駛</th>
            <th></th>
        </tr>
        <tbody>
            @foreach (var items in sendCars.Where(x => x.Level == 3 && x.ParentId == item.Id))
            {
                <tr>
                    
                    @*<td>@items.CarNoTime.CarNo</td>*@

                    @{
                string[] peoplearr = items.People.Split('、');
                Boolean havepeople = false;
                foreach (var peoplearritem in peoplearr)
                {
                    if (peoplearritem != "0:0")
                    {
                        havepeople = true;
                        break;
                    }
                }
                string[] timearr = items.CarNoTime.Time.Split('、');
                    }
                    <td>@timearr[0]</td>
                    @if (items.ChangeCars != null && havepeople)
                    {
                        string[] carid = items.ChangeCars.Split('、');
                        <td>
                            @for (int i = 0; i < carid.Length; i++)
                            {
                                <div>@carid[i]</div>
                            }
                        </td>

                    }
                    else if (items.Cars != null && havepeople)
                    {
                        string[] carid = items.Cars.Split('、');
                        <td>
                            @for (int i = 0; i < carid.Length; i++)
                            {
                                <div>@carid[i]</div>
                            }
                        </td>
                    }
                    else if (!havepeople)
                    {
                          <td>不發車</td>
                    }
                    else
                    {
                        if (items.CarNum == 0)
                        {
                        <td>選擇不派車</td>
                        }
                        else
                        {
                        <td>不發車</td>
                        }

                    }
                   @if (items.ChangeDrivers != null && havepeople)
                   {
                       string[] drivers = items.ChangeDrivers.Split('、');
                        <td>
                            @for (int i = 0; i < drivers.Length; i++)
                            {
                                int driverId = Convert.ToInt16(drivers[i]);
                                foreach (var driverlistitem in driverlist.Where(x => x.Id == driverId))
                                {
                                <div>@driverlistitem.Subject</div>
                                }

                            }
                        </td>
                   }
                   else if (items.Drivers != null && havepeople)
                   {
                       string[] drivers = items.Drivers.Split('、');
                        <td>
                            @for (int i = 0; i < drivers.Length; i++)
                            {
                                int driverId = Convert.ToInt16(drivers[i]);
                                foreach (var driverlistitem in driverlist.Where(x => x.Id == driverId))
                                {
                                <div>@driverlistitem.Subject</div>
                                }

                            }
                        </td>
                   }
                   else if (!havepeople)
                   {
                          <td>無</td>
                   }
                   else
                   {
                       if (items.CarNum == 0)
                       {
                        <td>選擇不派車</td>
                       }
                       else
                       {
                        <td>無</td>
                       }

                   }

                    <td>

                        @if (ViewBag.Have && items.Cars != null && items.Drivers != null)
                        {

                            DateTime sendcartime = Convert.ToDateTime(items.ParentSendCar.ParentSendCar.StartDate.GetValueOrDefault().Date.ToString("yyyy/MM/dd") + " " + Convert.ToDateTime(timearr[0]).ToString("HH:mm"));
                            if (DateTime.Now < sendcartime && havepeople)
                            {
                                     <input type="button" class="popup_btn btn btn-primary change" id="@items.Id" href="#ChangePanel" value="更換駕駛或車子"/>
                            }

                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
        }
    }
}
<div id="ChangePanel" class="popup_background">
    <div class="popup_content animated bounceInUp">
        <div class="closepop">

            <h3 style="color: white">更換駕駛或車子</h3>
        </div>
        <div class="banner">
            <div class="popup_tip" id="iframehref">



            </div>


        </div>

    </div>
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker();

        });
        $("#backSendcar").click(function () {
            location.href = '@Url.Action("Sendcarindex", "SendCar")';
 });
 $(".change").click(function () {
     var id = $(this).attr('id');
     var Classid = $("#ClassId").val()
     var iframehref = '<iframe src="http://ptdrts.myerstone.com.tw/SendCar/ChangeDriverCar?id=' + id + '" width="100%;" height="600px;" style=" border:none" ></iframe>';
     document.querySelector('#iframehref').innerHTML = iframehref;
 });
 $(".reload img").click(function () {
     window.location.reload();
 });
    </script>
}

PTBusToSchool/PtBusToSchool/Views/SendCar/Delete.cshtml
@model PtBusToSchool.Models.SendCar

@{
    ViewBag.Title = "刪除";
}

<h2>刪除</h2>

<h3 style="color:red;text-align: center;">你確定要刪除嗎?</h3>
<fieldset>
    <legend>SendCar</legend>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <div align="center">
        <input class="btn btn-primary" type="submit" value="刪除" /> 
        <input class="btn btn-primary" type="button" onclick="history.back()" value="回到上一頁" />
    </div>
}

PTBusToSchool/PtBusToSchool/Views/SendCar/SendCarDetails - 複製.cshtml
@using MvcPaging
@using PtBusToSchool.Models
@model List<PtBusToSchool.Models.SendCar>

@{
    ViewBag.Title = "派遣清單";
    List<SendCar> btnsendcar = ViewBag.sendcars;
    int i = 0;
    }

<style>
  .table th,
  .table td {
    text-align: center;
  }
  h2 .btn {
  	margin-right: 5px;
  }
</style>

<h2>@ViewBag.StartDate  



       @foreach (var item in btnsendcar)
       {

           foreach (var items in item.ChildSendCar)
           {
               
               i++;
               if (i == 1)
               {
                    Boolean YN = false;
                   foreach (var itemss in items.ChildSendCar)
                   {
                       if (itemss.CarNum.HasValue && itemss.CarNum >= 0)
                       {
                           YN = true;
                       }
                       else
                       {
                           YN = false;
                       }

                   }
                  
                     @items.LineName.CarId
                       <span>的派遣管理</span>

                
                   <div></div>
               }
               if (i != 1)
               {
                   Boolean YN = false;
                   foreach (var itemss in items.ChildSendCar)
                   {
                       if (itemss.CarNum.HasValue && itemss.CarNum >= 0)
                       {
                           YN = true;
                       }
                       else
                       {
                           YN = false;
                       }

                   }
                   if (YN)
                   {
                     
                            @Html.ActionLink(items.LineName.CarId, "SendCarDetails", new { id = items.Id, date = item.StartDate }, new { @class = "btn btn-primary" })
                      

                   }
                   else
                   {
                      
                              @Html.ActionLink(items.LineName.CarId, "SendCarDetails", new { id = items.Id, date = item.StartDate }, new { @class = "btn btn-danger" })
                     
                   }
               }


           }
       }

<input type="button" class="btn btn-primary" id="backSendcar" value="回派遣列表"/>

    </h2>


    <table class="table" style="width: 2000px">
        <tr>
       
          
            @{
                string[] carlinearr = ViewBag.carnotime.Split('→');
                      
            }

             <th>發車時間</th>
            @foreach (var item in carlinearr)
            {
                <th>@item</th>
            }
            
            
             
        </tr>
        <tbody>
       
           
        @foreach (var item in Model)
        {
            <tr>
              
             
                @{
            string[] peoplearr = item.People.Split('、');
            int total = 0;
            string[] timearr = item.CarNoTime.Time.Split('、');
 Boolean show = false;
                }
  @foreach (var items in peoplearr)
                {
                    if (items != "0:0")
                    {
                        show = true;
                        break;
                    }
                }
                @if (show)
                {
                <td>@timearr[0]<div>
                        @if (item.CarNum.HasValue && item.CarNum != 0)
                {
                   
                        @Html.ActionLink("已派"+item.CarNum+"台車", "Edit", new {id = item.Id}, new {@class = "btn btn-primary"}) 
           
                   
                }
                else
                {
                    if (item.CarNum == 0)
                    {
                        
                             @Html.ActionLink("選擇不派車", "Edit", new {id = item.Id}, new {@class = "btn btn-primary"}) 
           
                        
                    }
                    else
                    {
                        
                          @Html.ActionLink("派車", "Edit", new {id = item.Id}, new {@class = "btn btn-primary"}) <input type="button" class="btn btn-danger NoSend" id="@item.Id" value="不派車"/>
           
                  
                    }

                }

                        </div></td>
               foreach (var items in peoplearr)
                {


                    string[] updownpeople = items.Split(':');
                    total += Convert.ToInt16(updownpeople[0]) - Convert.ToInt16(updownpeople[1]);
                    if (updownpeople[0] == "0" && updownpeople[1] == "0")
                    {
                        <td></td>
                    }
                    else
                    {
                        <td>
                        <div>▲:@updownpeople[0] ▼:@updownpeople[1]</div>
                       <div>總:@total</div>
                    </td> 
                    }

                }
}
            </tr>
 
        }
        </tbody>
    </table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker();
        });
        $("#backSendcar").click(function () {
            location.href = '@Url.Action("Sendcarindex", "SendCar")';
        });
        $(".NoSend").click(function () {

            var sendCarId = $(this).attr("id");
            $.ajax({
                url: '@Url.Action("NoSend", "SendCar")',
                data: { id: sendCarId },
                   type: 'post',
                   cache: false,
                   async: false,
                   dataType: 'json',
                   success: function (data) {
                       if (data["Message"] === "Success") {
                           window.location.reload();
                        } 
                   }
               });

           });

    </script>
}